name: Linux Exploration

on:
  push:

jobs:
  explore:
    runs-on: ubuntu-latest

    steps:
      - name: Show current Directory
        run: pwd
      
      - name: List files
        run: ls -la

      - name: Show operating system
        run: uname -a 

      - name: Show user
        run: whoami